// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type LoginVerifyEmailData = {
    requestBody: VerifyEmail;
};

export type LoginVerifyEmailResponse = (Message);

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type VerifyEmail = {
    token: string;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    job_title?: (string | null);
    avatar_url?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    job_title?: (string | null);
    avatar_url?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    job_title?: (string | null);
    avatar_url?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    job_title?: (string | null);
    avatar_url?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkspaceCreate = {
    name: string;
    description?: (string | null);
};

export type WorkspaceUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type WorkspacePublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type WorkspacesPublic = {
    data: Array<WorkspacePublic>;
    count: number;
};

export type WorkspacesReadWorkspacesData = {
    limit?: number;
    skip?: number;
};

export type WorkspacesReadWorkspacesResponse = (WorkspacesPublic);

export type WorkspacesCreateWorkspaceData = {
    requestBody: WorkspaceCreate;
};

export type WorkspacesCreateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesReadWorkspaceData = {
    id: string;
    requestBody?: any; // Avoiding strict check or just ignore
};

export type WorkspacesReadWorkspaceResponse = (WorkspacePublic);

export type WorkspacesUpdateWorkspaceData = {
    id: string;
    requestBody: WorkspaceUpdate;
};

export type WorkspacesUpdateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesDeleteWorkspaceData = {
    id: string;
};

export type WorkspacesDeleteWorkspaceResponse = (Message);

export type ProjectCreate = {
    workspace_id: string;
    name: string;
    description?: (string | null);
    color?: (string | null);
    icon?: (string | null);
    is_private?: boolean;
};

export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
    color?: (string | null);
    icon?: (string | null);
    is_private?: (boolean | null);
};

export type ProjectPublic = {
    name: string;
    description?: (string | null);
    color?: (string | null);
    icon?: (string | null);
    is_private?: boolean;
    id: string;
    workspace_id: string;
    owner_id: string;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
    workspaceId?: (string | null);
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectData = {
    id: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    id: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type TaskCreate = {
    project_id: string;
    section_id?: (string | null);
    assignee_id?: (string | null);
    title: string;
    description?: (string | null);
    status?: string;
    priority?: string;
    due_date?: (string | null);
};

export type TaskUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (string | null);
    priority?: (string | null);
    due_date?: (string | null);
    section_id?: (string | null);
    assignee_id?: (string | null);
};

export type TaskPublic = {
    title: string;
    description?: (string | null);
    status: string;
    priority: string;
    due_date?: (string | null);
    id: string;
    project_id: string;
    section_id?: (string | null);
    owner_id: string;
    assignee_id?: (string | null);
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TasksReadTasksData = {
    limit?: number;
    skip?: number;
    projectId?: (string | null);
    assigneeId?: (string | null);
};


export type TasksReadTasksResponse = (TasksPublicWithProject);


export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksReadTaskData = {
    id: string;
};

export type TasksReadTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    id: string;
    requestBody: TaskUpdate;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    id: string;
};

export type TasksDeleteTaskResponse = (Message);

export type SectionCreate = {
    title: string;
    order?: number;
    project_id: string;
};

export type SectionUpdate = {
    title?: (string | null);
    order?: (number | null);
};

export type SectionPublic = {
    title: string;
    order: number;
    id: string;
    project_id: string;
};

export type SectionsPublic = {
    data: Array<SectionPublic>;
    count: number;
};

export type SectionsReadSectionsData = {
    limit?: number;
    skip?: number;
    projectId: string;
};

export type SectionsReadSectionsResponse = (SectionsPublic);

export type SectionsCreateSectionData = {
    requestBody: SectionCreate;
};

export type SectionsCreateSectionResponse = (SectionPublic);

export type SectionsUpdateSectionData = {
    id: string;
    requestBody: SectionUpdate;
};

export type SectionsUpdateSectionResponse = (SectionPublic);

export type SectionsDeleteSectionData = {
    id: string;
};

export type SectionsDeleteSectionResponse = (Message);

export type CommentCreate = {
    content: string;
    task_id: string;
};

export type CommentUpdate = {
    content?: (string | null);
};

export type CommentPublic = {
    content: string;
    id: string;
    task_id: string;
    user_id: string;
    created_at: string;
};

export type CommentsPublic = {
    data: Array<CommentPublic>;
    count: number;
};

export type CommentsReadCommentsData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type CommentsReadCommentsResponse = (CommentsPublic);

export type CommentsCreateCommentData = {
    requestBody: CommentCreate;
};

export type CommentsCreateCommentResponse = (CommentPublic);

export type CommentsDeleteCommentData = {
    id: string;
};

export type CommentsDeleteCommentResponse = (Message);

export type AttachmentBase = {
    file_name: string;
    file_path: string;
    file_type: string;
    file_size: number;
};

export type AttachmentPublic = {
    file_name: string;
    file_path: string;
    file_type: string;
    file_size: number;
    id: string;
    task_id: string;
    user_id: string;
    created_at: string;
};

export type InvitationCreate = {
    email: string;
    role?: string;
    status?: string;
    workspace_id: string;
};

export type InvitationPublic = {
    email: string;
    role?: string;
    status?: string;
    id: string;
    workspace_id: string;
    inviter_id: string;
    expires_at: string;
    created_at: string;
};

export type AttachmentsPublic = {
    data: Array<AttachmentPublic>;
    count: number;
};

export type AttachmentsReadAttachmentsData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type AttachmentsReadAttachmentsResponse = (AttachmentsPublic);

export type AttachmentsCreateAttachmentData = {
    taskId: string;
    formData: {
        file: Blob | File;
    };
};

export type AttachmentsCreateAttachmentResponse = (AttachmentPublic);

export type AttachmentsDeleteAttachmentData = {
    id: string;
};


export type AttachmentsDeleteAttachmentResponse = (Message);

export type WorkspaceMemberPublic = UserPublic & {
    role: string;
};

export type WorkspaceMembersPublic = {
    data: Array<WorkspaceMemberPublic>;
    count: number;
};

export type TaskPublicWithProject = TaskPublic & {
    project_name: string;
    project_color?: string | null;
};

export type TasksPublicWithProject = {
    data: Array<TaskPublicWithProject>;
    count: number;
};
